import { gameConfig } from "./gameConfig";

export const battleConfig = {
  fixedStepMs: 1000 / 120,
  player: {
    radius: 28,
    maxHealth: 100,
    moveSpeed: 228,
    fireCooldownMs: 180,
    minFireCooldownMs: 78,
    projectileSpeed: 900,
    projectileDamage: 34,
    muzzleOffset: 42,
    recoilKick: 7,
    recoilRecoveryPerSecond: 42,
    turretTurnSpeedRadiansPerSecond: 10.2,
  },
  enemy: {
    radius: 28,
    muzzleOffset: 38,
    patrolArrivalRadius: 24,
    investigateArrivalRadius: 28,
    repositionArrivalRadius: 36,
    nearbyDetectionRange: 228,
    investigateDurationMs: 2200,
    repositionDurationMs: 1000,
    archetypes: {
      chaser: {
        maxHealth: 76,
        moveSpeed: 126,
        fireCooldownMs: 920,
        projectileSpeed: 440,
        projectileDamage: 12,
        recoilKick: 4,
        recoilRecoveryPerSecond: 34,
        sightRange: 690,
        preferredRange: 280,
        engageRange: 640,
        aimInaccuracyRadians: 0.08,
        repositionDistance: 112,
        rewardCredits: 35,
        rewardScore: 140,
      },
      heavy: {
        maxHealth: 140,
        moveSpeed: 84,
        fireCooldownMs: 1180,
        projectileSpeed: 360,
        projectileDamage: 18,
        recoilKick: 4.5,
        recoilRecoveryPerSecond: 26,
        sightRange: 740,
        preferredRange: 350,
        engageRange: 680,
        aimInaccuracyRadians: 0.045,
        repositionDistance: 84,
        rewardCredits: 60,
        rewardScore: 240,
      },
      flanker: {
        maxHealth: 52,
        moveSpeed: 164,
        fireCooldownMs: 760,
        projectileSpeed: 470,
        projectileDamage: 10,
        recoilKick: 3.6,
        recoilRecoveryPerSecond: 40,
        sightRange: 620,
        preferredRange: 236,
        engageRange: 540,
        aimInaccuracyRadians: 0.13,
        repositionDistance: 168,
        rewardCredits: 45,
        rewardScore: 180,
      },
    },
  },
  projectile: {
    radius: 5,
    ttlMs: 1400,
  },
  pickup: {
    radius: 18,
    coinValue: 35,
    collectRadius: 34,
  },
  destructible: {
    healthBarVisibleMs: 1100,
    weakWallScore: 35,
    crateScore: 20,
  },
  upgrades: {
    maxHealthPerLevel: 20,
    movementSpeedPerLevel: 18,
    weaponDamagePerLevel: 5,
    visibilityRadiusTilesPerLevel: 0.55,
    fireRateReductionMsPerLevel: 22,
    turretRotationSpeedPerLevel: 1.45,
  },
  shop: {
    maxUpgradeLevel: 4,
  },
  difficulty: {
    rookie: {
      enemyHealthMultiplier: 0.84,
      enemyDamageMultiplier: 0.82,
      enemyFireCooldownMultiplier: 1.08,
    },
    normal: {
      enemyHealthMultiplier: 1,
      enemyDamageMultiplier: 1,
      enemyFireCooldownMultiplier: 1,
    },
    ace: {
      enemyHealthMultiplier: 1.18,
      enemyDamageMultiplier: 1.16,
      enemyFireCooldownMultiplier: 0.92,
    },
  },
  world: {
    maxSimulationDeltaMs: 64,
  },
  visibility: {
    tileSize: gameConfig.gridSize,
    worldWidth: gameConfig.worldWidth,
    worldHeight: gameConfig.worldHeight,
    radiusTiles: 3.4,
    refreshDistance: 18,
  },
} as const;
