import { gameConfig } from "./gameConfig";

export const battleConfig = {
  fixedStepMs: 1000 / 120,
  player: {
    radius: 28,
    maxHealth: 100,
    moveSpeed: 228,
    fireCooldownMs: 180,
    projectileSpeed: 900,
    projectileDamage: 34,
    muzzleOffset: 42,
    recoilKick: 7,
    recoilRecoveryPerSecond: 42,
  },
  enemy: {
    radius: 28,
    muzzleOffset: 38,
    patrolArrivalRadius: 24,
    investigateArrivalRadius: 28,
    repositionArrivalRadius: 36,
    nearbyDetectionRange: 228,
    investigateDurationMs: 2200,
    repositionDurationMs: 1000,
    archetypes: {
      chaser: {
        maxHealth: 76,
        moveSpeed: 126,
        fireCooldownMs: 920,
        projectileSpeed: 440,
        projectileDamage: 12,
        recoilKick: 4,
        recoilRecoveryPerSecond: 34,
        sightRange: 690,
        preferredRange: 280,
        engageRange: 640,
        aimInaccuracyRadians: 0.08,
        repositionDistance: 112,
        rewardCredits: 35,
      },
      heavy: {
        maxHealth: 140,
        moveSpeed: 84,
        fireCooldownMs: 1180,
        projectileSpeed: 360,
        projectileDamage: 18,
        recoilKick: 4.5,
        recoilRecoveryPerSecond: 26,
        sightRange: 740,
        preferredRange: 350,
        engageRange: 680,
        aimInaccuracyRadians: 0.045,
        repositionDistance: 84,
        rewardCredits: 60,
      },
      flanker: {
        maxHealth: 52,
        moveSpeed: 164,
        fireCooldownMs: 760,
        projectileSpeed: 470,
        projectileDamage: 10,
        recoilKick: 3.6,
        recoilRecoveryPerSecond: 40,
        sightRange: 620,
        preferredRange: 236,
        engageRange: 540,
        aimInaccuracyRadians: 0.13,
        repositionDistance: 168,
        rewardCredits: 45,
      },
    },
  },
  projectile: {
    radius: 5,
    ttlMs: 1400,
  },
  pickup: {
    radius: 18,
    coinValue: 35,
    collectRadius: 34,
  },
  destructible: {
    healthBarVisibleMs: 1100,
  },
  upgrades: {
    armorHealthPerLevel: 18,
    movementSpeedPerLevel: 18,
    opticsRadiusTilesPerLevel: 0.45,
    turretDamagePerLevel: 4,
    turretCooldownReductionMsPerLevel: 18,
  },
  shop: {
    maxUpgradeLevel: 3,
    prices: {
      armor: [65, 105, 155],
      optics: [55, 95, 145],
      movement: [60, 100, 150],
      turret: [70, 120, 180],
    },
  },
  world: {
    maxSimulationDeltaMs: 64,
  },
  visibility: {
    tileSize: gameConfig.gridSize,
    worldWidth: gameConfig.worldWidth,
    worldHeight: gameConfig.worldHeight,
    radiusTiles: 3.4,
    refreshDistance: 18,
  },
} as const;
